### ISSUE TITLE
【算法与数据结构项目推荐】Algorithms-in-4-Steps

### ISSUE THREAD

**Issue by Xunzhuo** [Snailclimb/awesome-java#10]
Link: https://github.com/Xunzhuo/Algorithms-in-4-Steps
OI_Sharing：算法与数据结构的课件、书籍、论文、习题、OJ网站的汇总，并总结了学习路线

**Comment by Snailclimb** [comment]
> Link: https://github.com/Xunzhuo/Algorithms-in-4-Steps
> OI_Sharing：算法与数据结构的课件、书籍、论文、习题、OJ网站的汇总，并总结了学习路线

已经收录！LGTM👍
