### ISSUE TITLE
自荐一个Java学习的项目

### ISSUE THREAD

**Issue by freestylefly** [Snailclimb/awesome-java#11]
作者工作后费劲千辛万苦转行的学习经验吐血整理，适合转行人群
https://github.com/freestylefly/javaStudy

**Comment by Snailclimb** [comment]
> 作者工作后费劲千辛万苦转行的学习经验吐血整理，适合转行人群
> https://github.com/freestylefly/javaStudy

感觉还不是特别完善啊。
